# Generated by Django 4.1.5 on 2023-01-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя компьютера')),
                ('ip', models.CharField(max_length=100, verbose_name='IP компьютера')),
                ('mac_adress', models.CharField(max_length=100, verbose_name='MAC компьютера')),
                ('description', models.TextField(verbose_name='Информация о пк')),
                ('date_connection', models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения')),
                ('on_active', models.BooleanField(default=False, verbose_name='Активен ли')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя диска')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя диска')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('range', models.IntegerField(verbose_name='Объем диска')),
                ('user_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.userpc')),
            ],
            options={
                'verbose_name': 'Диск',
                'verbose_name_plural': 'Диски',
            },
        ),
    ]
