# Generated by Django 4.1.5 on 2023-01-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное имя диска'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='range',
            field=models.IntegerField(null=True, verbose_name='Объем диска'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Серийный номер'),
        ),
    ]
