# Generated by Django 4.1.5 on 2023-01-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pc', '0003_remove_disk_full_name_disk_free_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True, verbose_name='Содержимое диска')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.disk')),
            ],
        ),
    ]
