# Generated by Django 4.1.5 on 2023-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_disk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadisk',
            name='name',
            field=models.CharField(default='null', max_length=100, verbose_name='Имя диска'),
            preserve_default=False,
        ),
    ]
