# Generated by Django 4.1.5 on 2023-01-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_disk', '0004_datadisk_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadisk',
            name='waiting_response',
            field=models.BooleanField(default=False, verbose_name='Ожидает запрос'),
        ),
    ]
