# Generated by Django 4.1.5 on 2023-01-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_disk', '0006_remove_datadisk_waiting_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadisk',
            name='path',
            field=models.CharField(max_length=350, verbose_name='Текущий путь'),
        ),
    ]
