# Generated by Django 4.1.5 on 2023-01-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_remove_disk_full_name_disk_free_range'),
        ('hard_disk', '0007_alter_datadisk_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField(default=False, verbose_name='Ответил ли')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.userpc')),
            ],
        ),
    ]
