# Generated by Django 4.1.5 on 2023-01-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_remove_disk_full_name_disk_free_range'),
        ('hard_disk', '0008_requestpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpc',
            name='pc',
        ),
        migrations.AddField(
            model_name='requestpc',
            name='disk',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='pc.disk'),
            preserve_default=False,
        ),
    ]
