# Generated by Django 4.1.5 on 2023-01-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hard_disk', '0010_requestpc_is_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestpc',
            old_name='request',
            new_name='state',
        ),
    ]
