# Generated by Django 4.1.5 on 2023-01-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hard_disk', '0011_rename_request_requestpc_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadisk',
            name='file_path',
            field=models.CharField(max_length=350, null=True, verbose_name='Текущий путь файла'),
        ),
    ]
