# Generated by Django 4.1.5 on 2023-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя компьютера')),
                ('ip', models.CharField(max_length=100, verbose_name='IP компьютера')),
                ('mac_adress', models.CharField(max_length=100, verbose_name='MAC компьютера')),
                ('description', models.TextField(verbose_name='Информация о пк')),
                ('date_connection', models.DateTimeField(verbose_name='Дата подключения')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
