# Generated by Django 4.1.5 on 2023-01-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_alter_userpc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpc',
            options={'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AddField(
            model_name='userpc',
            name='on_active',
            field=models.BooleanField(default=False, verbose_name='Активен ли'),
        ),
        migrations.AlterField(
            model_name='userpc',
            name='date_connection',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения'),
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя диска')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя компьютера')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('range', models.IntegerField(verbose_name='Объем диска')),
                ('user_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.userpc')),
            ],
            options={
                'verbose_name': 'Диск',
                'verbose_name_plural': 'Диски',
            },
        ),
    ]
