# Generated by Django 4.1.5 on 2023-01-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_alter_userpc_options_userpc_on_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное имя диска'),
        ),
    ]
